# Generated by Django 4.2.7 on 2025-06-18 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawTranscriptCache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fireflies_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("raw_fireflies_data", models.JSONField()),
                ("cache_timestamp", models.DateTimeField(auto_now_add=True)),
                ("meeting_date", models.DateTimeField()),
                ("meeting_title", models.CharField(blank=True, max_length=500)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("processed", models.BooleanField(default=False)),
                ("processing_errors", models.JSONField(default=list)),
                ("data_hash", models.CharField(db_index=True, max_length=64)),
                ("is_valid", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_raw_transcript_cache",
                "indexes": [
                    models.Index(
                        fields=["fireflies_id"], name="core_raw_tr_firefli_ef2d57_idx"
                    ),
                    models.Index(
                        fields=["meeting_date", "processed"],
                        name="core_raw_tr_meeting_bd6fec_idx",
                    ),
                    models.Index(
                        fields=["cache_timestamp"],
                        name="core_raw_tr_cache_t_c9823f_idx",
                    ),
                    models.Index(
                        fields=["data_hash"], name="core_raw_tr_data_ha_7c6da4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProcessedTaskData",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_item", models.CharField(max_length=500)),
                ("assignee_emails", models.CharField(blank=True, max_length=500)),
                ("assignee_full_names", models.CharField(blank=True, max_length=500)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("brief_description", models.TextField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("To Do", "To Do"),
                            ("Stuck", "Stuck"),
                            ("Working on it", "Working on it"),
                            ("Waiting for review", "Waiting for review"),
                            ("Approved", "Approved"),
                            ("Done", "Done"),
                        ],
                        default="To Do",
                        max_length=20,
                    ),
                ),
                ("extraction_confidence", models.FloatField(default=0.0)),
                ("source_sentences", models.JSONField(default=list)),
                ("processing_notes", models.TextField(blank=True)),
                ("monday_item_id", models.CharField(blank=True, max_length=100)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_status", models.CharField(default="pending", max_length=50)),
                ("delivery_errors", models.JSONField(default=list)),
                ("human_approved", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_processed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_tasks",
                        to="core.transcript",
                    ),
                ),
            ],
            options={
                "db_table": "core_processed_task_data",
                "indexes": [
                    models.Index(
                        fields=["transcript", "status"],
                        name="core_proces_transcr_1e49d7_idx",
                    ),
                    models.Index(
                        fields=["priority", "due_date"],
                        name="core_proces_priorit_4a8f5a_idx",
                    ),
                    models.Index(
                        fields=["human_approved", "delivery_status"],
                        name="core_proces_human_a_63f412_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_proces_created_f93ec9_idx"
                    ),
                ],
            },
        ),
    ]
