# Generated by Django 4.2.7 on 2025-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rawtranscriptcache_processedtaskdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionitem",
            name="monday_item_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-filled when delivered to Monday.com",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processedtaskdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("Stuck", "Stuck"),
                    ("Deprioritized", "Deprioritized"),
                    ("Working on it", "Working on it"),
                    ("Done", "Done"),
                    ("Waiting for review", "Waiting for review"),
                    ("Approved", "Approved"),
                    ("To Do", "To Do"),
                    ("Review", "Review"),
                ],
                default="To Do",
                max_length=20,
            ),
        ),
    ]
