# Generated by Django 4.2.7 on 2025-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_update_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedtaskdata",
            name="source_sentences",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
