# Generated by Django 4.2.7 on 2025-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_gemini_processed_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="assignee_emails",
            field=models.CharField(
                default="",
                help_text="Comma-separated email addresses of assignees",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="assignee_full_names",
            field=models.CharField(
                default="",
                help_text="Comma-separated full names of assignees",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="delivered_to_monday",
            field=models.BooleanField(
                default=False, help_text="True if task has been delivered to Monday.com"
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="delivery_errors",
            field=models.JSONField(
                default=list, help_text="List of delivery errors if any occurred"
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="delivery_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when task was delivered to Monday.com",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="extraction_confidence",
            field=models.FloatField(
                default=0.0,
                help_text="Confidence score from 0.0 to 1.0 for extraction quality",
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="gemini_model_version",
            field=models.CharField(
                default="gemini-2.5-flash",
                help_text="Gemini model version used for extraction",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="monday_item_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Monday.com item ID after successful delivery",
                max_length=100,
            ),
        ),
    ]
