# Generated by Django 4.2.7 on 2025-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_update_gemini_task_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="geminiprocessedtask",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Approval status for auto-push functionality",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="geminiprocessedtask",
            name="auto_mute_enabled",
            field=models.BooleanField(
                default=False, help_text="Mute automatic pushing (disable auto-push)"
            ),
        ),
        migrations.AddField(
            model_name="geminiprocessedtask",
            name="auto_push_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable automatic pushing to Monday.com when approved",
            ),
        ),
        migrations.AddField(
            model_name="geminiprocessedtask",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason for rejection if status is rejected",
            ),
        ),
    ]
