# Generated by Django 4.2.7 on 2025-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_auto_push_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="assignee_emails",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated email addresses of assignees",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="assignee_full_names",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Comma-separated full names of assignees",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="brief_description",
            field=models.TextField(
                blank=True,
                help_text="30-50 words, human tone, begins with '<Assigner Full Name> asked <Assignee First Name>...'",
            ),
        ),
        migrations.AlterField(
            model_name="geminiprocessedtask",
            name="task_item",
            field=models.CharField(
                blank=True,
                help_text="At least 10 natural, coherent words describing the task",
                max_length=1000,
            ),
        ),
    ]
